import random

from typing import List

class Generator:
    def __init__(self) -> None:
        # country code, you can add more code country here
        self.code: List[str] = ["bt", "id", "kt", "pn"]
        
        # 'sifat' mean characteristic or 'trait' in english
        self.sifat: list = random.choice([
            "lucu", "cepat", "marah", 
            "dingin", "nakal", "lambat", 
            "galak", "imut", "jahil", "ramah",
            "liar", "aneh", "berani"
        ])
        
        # 'benda' mean object like 'chair' or something like that.
        self.benda: list = random.choice([
            "kucing", "robot", "ninja", 
            "kodok", "pirat", "monyet", 
            "gajah", "bajaklaut", "panda", 
            "serigala", "alien", "naga"
        ])
        
        # general wordlist indonesian, combined with name of lot a people, city name, village name, string number and combined with unique name 
        # unique name like 'konoha' from naruto seriues :D
        self.wordlist = [
	        'abiyah', 'abdilla', 'aca', 'acha', 'acaa', 'achaa', 'ai', 'aii', 'adawiah', 'adawiyah', 'ade', 'adel', 'adell', 'adel', 'adellaa', 'adelia', 'adellia', 'adeliya', 'adiba', 'adifa', 'adinda', 'aeni', 'aidah', 'aini', 'ainun', 'aira', 'asiah', 'aisah', 'aisyah', 'afifah', 'afipah', 'alawiah', 'alawiyah', 'alfatunisa', 'alfatunnisa', 'agnes', 'agnesia', 'ajahra', 'ajeng', 'ajeung', 'ajig', 'ajijah', 'ajizah', 'ajg', 'alesha', 'alia', 'alika', 'alimah', 'aliya', 'alifa', 'alifah', 'aliva', 'alivah', 'aliyah', 'almeera', 'almira', 'ama', 'amalia', 'amaliag', 'amaliyah', 'amanda', 'amidah', 'amira', 'aminah', 'ana', 'anantasia', 'anantasya', 'anastasia', 'anastasya', 'agnes', 'andini', 'ani', 'anisa', 'anita', 'any', 'anying', 'anyun', 'angela', 'angelina', 'anggraeni', 'anggraini', 'anggi', 'anggita', 'anggun', 'anjas', 'anjasmara', 'anjay', 'anugerah', 'anugrah', 'anjing', 'apifah', 'apipah', 'april', 'aprilia', 'aprillia', 'apriliani', 'apriliyani', 'aprilianti', 'apriliyanti', 'aqila', 'aqilla', 'ara', 'arra', 'arafah', 'arrafah', 'areta', 'aretha', 'arofah', 'arin', 'arini', 'ariani', 'arista', 'ariyani', 'aryani', 'aryanti', 'arianti', 'ariyanti', 'arumi', 'arsita', 'arsyita', 'arsila', 'asyila', 'asypa', 'asifa', 'asipa', 'asmi', 'asmara', 'asih', 'asilah', 'asti', 'astiani', 'astiyani', 'astuti', 'atik', 'atika', 'atikah', 'ayg', 'ayank', 'ayang', 'ayra', 'ayu', 'ayyu', 'ayunda', 'ayuni', 'ayudia', 'ayudiya', 'ayudiah', 'ayuningsih', 'azzahra', 'azijah', 'azizah', 'azmi', 'azmy', 'azura',
	        'babi', 'baby', 'badriah', 'bajingan', 'bagong', 'bandung', 'bngst', 'bangsat', 'bela', 'bella', 'bibah', 'bila', 'billa', 'belinda', 'betharia', 'bintang', 'briana', 'britania', 'briela', 'briyana', 'budiarti', 'bulan', 'bunga', 'bungsu', 'bunyamin', 'butet',
	        'ca', 'cabi', 'cabhy', 'caby', 'cabby', 'caca', 'cca', 'cahaya', 'cahya', 'cahyani', 'cahyaningsih', 'caitlyn', 'camelia', 'cangcut', 'can', 'cans', 'canss', 'cantik', 'cantika', 'caroline', 'charrisa', 'catherine', 'cassandra', 'celine', 'cecilia', 'celsi', 'celsie', 'centil', 'chaca', 'chacha', 'chelsi', 'chelsie', 'chelsea', 'chesi', 'chessy', 'chika', 'cia', 'cci', 'cici', 'cika', 'cimok', 'cindy', 'cinta', 'cintia', 'cintaku', 'cintya', 'cintiya', 'citra', 'chindy', 'claudya', 'cucu', 'ccu', 'culun', 'cupu', 'cynthia', 'cyntia',
	        'dafin', 'dahlia', 'daiba', 'dania', 'daniah', 'daniyah', 'danyyah', 'daswita', 'dara', 'davina', 'darsie', 'dawy', 'de', 'dea', 'dede', 'dela', 'della', 'delia', 'delicia', 'denia', 'deniah', 'deniyah', 'deon', 'debi', 'deby', 'debby', 'denita', 'denisa', 'devi', 'devia', 'devie', 'desnia', 'desnie', 'divita', 'desi', 'desita', 'deswita', 'dewandana', 'dwi', 'dewi', 'dewita', 'dhairya', 'dhara', 'dhe', 'dhea', 'dheniah', 'dhewi', 'dhita', 'dhiya', 'dia', 'diah', 'diajeng', 'dian', 'diana', 'diandra', 'diannova', 'dias', 'diinah', 'dika', 'diksa', 'dila', 'dilla', 'dipa', 'diva', 'dianda', 'dila', 'dilla', 'dira', 'dina', 'dinda', 'dini', 'diniah', 'diniyah', 'disa', 'disha', 'dita', 'divya', 'dixha', 'diya', 'diyah', 'diyara', 'dnya', 'dona', 'dyra', 'dyah', 'dzafina', 'djakarta',
	        'eka', 'elailah', 'elaina', 'eira', 'eisha', 'elaina', 'elda', 'elea', 'elena', 'eleanor', 'eleanoer', 'eleha', 'eletha', 'elfie', 'elga', 'elia', 'eliana', 'elicia', 'elika', 'elin', 'elina', 'elisabeth', 'elis', 'ellis', 'elise', 'eliya', 'eliza', 'elizabeth', 'ella', 'ellen', 'elliana', 'ellie', 'elma', 'elmira', 'elora', 'elisa', 'elisha', 'elisia', 'elisiya', 'elisya', 'elisyha', 'elsye', 'elfina', 'elsa', 'evi', 'epi', 'elisabeth', 'elin', 'elsy', 'elva', 'elvira', 'elly' 'elvina', 'elzahra', 'embun', 'emeline', 'ekavira', 'emery', 'emi', 'emilia', 'emy', 'emyliya', 'ema', 'emma', 'emily', 'emira', 'endah', 'endang', 'epi', 'erna', 'erni', 'eri', 'erika', 'erina', 'erlinda', 'esti', 'estiana', 'eis', 'eti', 'etie', 'ety', 'euis', 'eva', 'evi', 'evita', 'evitamala', 'evalina', 'evelyn', 'ewe',
	        'fara', 'farah', 'farrah', 'fadila', 'fadla', 'fadhila', 'fadhla', 'faija', 'faiza', 'faizza', 'faizah', 'fani', 'fanni', 'fany', 'fanny', 'fanya', 'farhah', 'farhana', 'farida', 'faridha', 'fasya', 'fasha', 'fathia', 'fatin', 'fatina', 'fatthyyah', 'faujia', 'faujiah', 'fauzia', 'fauziah', 'fauziya', 'fauzyah', 'fawziyah', 'fazila', 'fazilla', 'fazeela', 'fatim', 'fatima', 'fatimah', 'fathimah', 'felisia', 'felisya', 'ferli', 'ferly', 'ferlyani', 'fika', 'fina', 'fiona', 'fionna', 'fida', 'fira', 'firli', 'firly', 'firlly', 'firliani', 'firliyani', 'fita', 'fitri', 'fitriani', 'fitriyani', 'fitryani', 'fiska', 'fizka', 'fiza', 'frisilia', 'frisiliya', 'freya', 'friska', 'fuji', 'fuzi',
	        'gabriella', 'gaby', 'gabby', 'garut', 'gadis', 'geby', 'gebby', 'gelsey', 'gendis', 'gemma', 'georgia', 'gloria', 'gea', 'ghwa', 'gia', 'ghia', 'ghina', 'ghita"', 'gina', 'ginna', 'gisela', 'gisella', 'gita', 'gitta', 'grace', 'gracia','grachelyn','gracheline', 'graciella', 'greta', 'gresia', 'gresik', 'glenda', 'gloria', 'giska', 'greta', 'ganesha', 'geisha', 'genta', 'gwendolyn',
	        'habibah', 'harika', 'hafsa', 'halima', 'halia', 'halimah', 'hafiza', 'hafsah', 'hafiza', 'hafizah', 'hana', 'handayani', 'handayanti', 'hanna', 'hannah', 'hani', 'hany', 'hanny', 'hanifah', 'hanipah', 'haila', 'hayla', 'hania', 'haniya', 'hartini', 'hasanah', 'hatima', 'hatimah', 'hilda', 'hilma', 'hilmawati', 'hiya', 'helen', 'helena', 'hellen', 'helia', 'helin', 'helina', 'hemalia', 'hepti', 'hesa', 'hessa', 'hesha', 'hesti', 'hestia', 'hesty', 'helga', 'hasna', 'hinata', 'hikmat', 'hopi', 'hopipah', 'hoho', 'hotima', 'hotimah', 'hikmah', 'humaida', 'humayda', 'husna', 'hurairah',
	        'ica', 'icaa', 'icha', 'ichaa', 'ida', 'ifa', 'iffa', 'ilmira', 'ina', 'inna', 'inaara', 'inara', 'inarah', 'inayah', 'indah', 'indira', 'indyra', 'indri', 'indry', 'insan', 'insani', 'imelda', 'ina', 'irma', 'irena', 'ika', 'ijah', 'intan', 'intanrahayu', 'ira', 'isabela', 'isabella', 'isan', 'isana', 'isyana', 'isah', 'isma', 'ismawati', 'ismawaty', 'ismi', 'ismiya', 'ismiyati', 'isnaen', 'isnaeni', 'isni', 'iza', 'izah', 'izna', 'iysha',
	        'jafira', 'jahira', 'jalilah', 'jahra', 'jamilah', 'janeta', 'jameela', 'jannah', 'janita', 'jasmin', 'jasmine', 'jayanti', 'jelita', 'jeni', 'jeny', 'jenny', 'jennifer', 'jenita', 'jennita', 'jesica', 'jesicca', 'jesika', 'jihan', 'jihana', 'jingga', 'juwita', 'juli', 'julia', 'juliana', 'juliet', 'jumaina', 'jumainah', 'juniarti', 'junaina', 'juwitta', 'jwita',
	        'kaila', 'kalia', 'kaira', 'khaira', 'karin', 'karina', 'kartika', 'kadek', 'kania', 'kaniya', 'kartini', 'kasih', 'kamala', 'kamila', 'karima', 'karomah', 'karisa', 'karissa', 'karsih', 'katrina', 'keira', 'khaira', 'khaila', 'khafifah', 'khadijah', 'khairun', 'khairunisa', 'khalifah', 'khalilah', 'khabirah', 'khatimah', 'khofiroh', 'khopipah', 'kiki', 'kim', 'kiara', 'kila', 'killa', 'kira', 'kirani', 'komarudin', 'kumala', 'kumalasari', 'kokom', 'komala', 'komalasari', 'komalawati', 'kontol', 'kotima', 'kotimah', 'kulsum', 'kultsum', 'kuntul', 'kurnia', 'kurniati', 'kurniyati', 'kursina', 'kurniasih', 'kusina', 'kusmiati', 'kusmiyai',
            'laela', 'laesa', 'lady', 'lafiza', 'lala', 'laila', 'lati', 'laty', 'latifah', 'lathifah', 'layla', 'lara', 'laras', 'larasati', 'lasmini', 'laura', 'laudia', 'laudya', 'leila', 'lela', 'lesmana', 'lesmana', 'lena', 'leni', 'lenka', 'leny', 'lenny', 'lestari', 'lestarty', 'lesti', 'lesty', 'levita', 'lia', 'lida', 'lidia', 'lidya', 'liana', 'liani', 'lilis', 'lina', 'linda', 'lintang', 'lis', 'lisa', 'lisha', 'lisna', 'lisnawati', 'lisnawaty', 'listi', 'listy', 'listia', 'listya', 'liza', 'liya', 'liyani', 'liza', 'lomrah', 'lola', 'lolita', 'luci', 'lucia', 'lucy', 'lucya', 'lulu', 'luna', 'lusi', 'lusy', 'luvita', 'lyan', 'lyna', 'lysa',
            'mae', 'maemunah', 'maesarah', 'maesaroh', 'mala', 'maida', 'maidah', 'maira', 'maisa', 'maisha', 'malika', 'maimunah', 'magfirah', 'mahalini', 'maharani', 'maharini', 'mahda', 'manda', 'mandha', 'maria', 'mardiah', 'mardianti', 'mardiyanti', 'mardyah', 'mardiyah', 'mariah', 'mariam', 'mariyah', 'maryati', 'mariati', 'mariyati', 'markonah', 'mariyam', 'marisa', 'marissa', 'martina', 'martinah', 'martini', 'maryamah', 'marwah', 'maryanti', 'marwati',  'marwaty', 'marzia', 'marziya', 'masitoh', 'masriah', 'masriyah', 'maulida', 'maulidia', 'maulidya', 'maulidiya', 'mawar', 'maya', 'mayra', 'maymuna', 'maymunah', 'marziah', 'meca', 'mecca', 'meka', 'medina', 'mega', 'megan', 'melani', 'melany', 'melina', 'meli', 'melinda', 'melisa', 'melly', 'merry', 'mia', 'mieta', 'mietaa', 'mila', 'mimin', 'mira', 'miraa', 'mirna', 'miranda', 'miya', 'mufliha', 'muna', 'munawarah', 'munawwarah', 'munawaroh', 'murni', 'murniati', 'murniyati', 'muslima', 'mulimah', 'muti', 'mutmainah', 'muthmainnah', 'mutmaidah', 'muthmaidah', 'mutia', 'mutiara',
            'nabila', 'nada', 'nadhin', 'nadia', 'nadira', 'nadhira', 'nadin', 'nadiya', 'nafisa', 'nafisha', 'nafisah', 'nagita', 'naila', 'naira', 'najwa', 'nana', 'nanda', 'nani', 'natalia', 'nataliya', 'natasia', 'natasya', 'natasyha', 'nasa', 'naura', 'nayara', 'nayyara', 'nayra', 'nayla', 'naswa', 'nashwa', 'nasywa', 'nazwa', 'nia', 'nida', 'nifa', 'nina', 'nindi', 'nindy', 'ningrum', 'ningsih', 'nita', 'nitatalia', 'niken', 'nisa', 'nissa', 'nurul', 'nopi', 'novi', 'novita', 'nurull', 'nunung', 'nuri', 'nurianti', 'nurjanah', 'nurjannah', 'nuryanti',
            'oca', 'octa', 'octavia', 'olivia', 'ollivia', 'oliv', 'olive', 'olla', 'okta', 'oktavia', 'ocha', 'odie', 'omaira', 'ogut', 'xabiya', 'xaviera', 'xavira', 'xena', 'xiao', 'xyla',
            'padma', 'putri', 'puspa', 'pipit', 'prita', 'paras', 'paramita' 'permata','permatasari', 'purnama', 'purnamasari', 'puspa','putri', 'puteri', 'pitri', 'pratiwi', 'pramita', 'priyanka',
            'qaidah', 'qaila', 'qailla', 'qanita', 'qasidah', 'qasimah', 'qiana', 'qiani', 'qila', 'qilla', 'qiqi', 'qonita', 'qori', 'qoriah', 'qoriyah', 'qosamah', 'qosimah', 'qalesya',
            'ra', 'raa', 'raina', 'rana', 'rabiah', 'rabiyah', 'rafa', 'raisa', 'raiqah', 'raimah', 'rahma', 'rahmah', 'rahmaa', 'rahmawati', 'rahmawaty', 'rhma', 'rahnadani', 'rahmadhani', 'ramadani', 'ramadhani', 'rani', 'rany', 'raniah', 'rasya', 'rati', 'ratifah', 'rara', 'rere', 'refa', 'repa', 'reva', 'repani', 'revani', 'rena', 'renatri', 'reni', 'renata', 'rani', 'ratna', 'raya', 'rina', 'rida', 'rifda', 'rifdah', 'rini', 'ririn', 'rianti', 'rianty', 'riyanti', 'riyanty', 'riska', 'rizka', 'rohma', 'rohmah', 'rohmawati', 'rohmawaty', 'rona', 'rosdiana', 'rosdiani', 'ross', 'rossa', 'rosita', 'rosalina', 'rossalina', 'rosmanah', 'rum', 'rumaidah', 'ruwaidah', 'ryzka',
            'sadiya', 'sabira', 'sabhira', 'sahara', 'saharah', 'sahla', 'saleha', 'saila', 'salima', 'salimah', 'sabha', 'sabrina', 'safa', 'saffa', 'safna', 'safira', 'saidah', 'sahira', 'sakila', 'sakinah', 'sakira', 'salma', 'salmaira', 'salsa', 'salsabila', 'salsabilla', 'salsabylla', 'salwa', 'santi', 'sani', 'santy', 'santika', 'sara', 'shafira', 'shavira', 'shakira', 'shalina', 'shafna', 'shafana', 'shaleha', 'shalehah', 'shakeera', 'shakila', 'shalihah', 'shanti', 'shanty', 'shantika', 'shani', 'shaniyah', 'shofy', 'shofiyah', 'shofiyyah', 'sholeha', 'sholehah', 'sifa', 'silawati', 'sipa', 'silpi', 'silvi', 'siska', 'sinta', 'suci', 'selly', 'safitri', 'saputri', 'sarah', 'saras', 'sarasvati', 'saraswati', 'sari', 'sasmita', 'setiawati', 'sisil', 'siti', 'sity', 'siregar', 'simanjuntak', 'solha', 'solehah', 'sonia', 'soraya', 'sukma', 'suci', 'sumi', 'sumiyati', 'suraya', 'suraiya', 'suratni', 'surtini', 'suratmi', 'sasanti', 'susanty', 'susi', 'susilawati', 'susilawaty', 'susy', 'sutari', 'suteni', 'susu', 'syafaa', 'syakila', 'syakira', 'syifa', 'sypa', 'sya', 'syahla', 'syahira', 'syafira', 'syavira',
            'tabita', 'tabhita', 'tahira', 'tahiya', 'tahiyyah', 'talea', 'talia', 'taliah', 'talita', 'talitha', 'tami', 'tamimah', 'tammy', 'tania', 'tannia', 'taniya', 'tari', 'tarisa', 'tarissa', 'tasya', 'taskia', 'taskiya', 'taskya', 'tazkia', 'tazkiya', 'tazkya', 'tesa', 'tessa', 'tea', 'thea', 'thiara', 'tia', 'tiaa', 'tias', 'tiastuti', 'tiara', 'tifani', 'tifany', 'tifanni', 'tifanny', 'tiffani', 'tika', 'tina','tita', 'titian', 'titi', 'titie', 'titisari', 'titin', 'tri', 'tria', 'triani', 'tsabitah', 'tsunade', 'tusilawati', 'tuti', 'tya', 'tiktok', 'tikotok', 'tyz', 'tzy',
            'uci', 'uchi', 'ufaira', 'ufairah', 'ulfa', 'ulfaqiha', 'ulan', 'ullan', 'ulandari', 'ulandary', 'ulima', 'ulia', 'uliya', 'ulya', 'ulpah', 'ulpa', 'ulva', 'umayah', 'umi', 'umy', 'ummi', 'ummy', 'umiyah', 'umiati', 'umiaty', 'umiyati', 'utami', 'utari', 'ute', 'ubaidah', 'umaira', 'umairah', 'usna', 'usnah', 'uswah', 'uswatun', 'uswatunhasanah', 'uzwatun',
            'va', 'vaa', 'vani', 'vaeda', 'vanni', 'vania', 'vannia', 'vaniya', 'vanniya', 'vany', 'vanya', 'valen', 'vallen', 'valentina', 'vallentina', 'valeria', 'vanesa', 'vannesa', 'vanda', 'vardah', 'vahira', 'vazza', 'verda', 'vera', 'victoria', 'viktoria', 'via', 'vina', 'vinna', 'vivi', 'vivie', 'vianita', 'viviana', 'viena', 'viola', 'vivianna', 'vida', 'vio', 'violet', 'violetta', 'veronica', 'veronika', 'viani', 'vianika', 'viane', 'verona', 'viana', 'viera', 'valencia', 'valensia', 'viata', 'vira', 'virania', 'vita', 'vitta', 'vitaloka', 'velma', 'vilmei', 'vega', 'viona', 'visi',
            'wafa', 'wafda', 'wafiyah', 'wahdah', 'waheeda', 'wardani', 'wardhani', 'wahdaniyah', 'wahidah', 'wanda', 'wangi', 'wardah', 'wasfa', 'washfa', 'wasiah', 'wasimah', 'wasiyah', 'wastiqah', 'wati', 'watiah', 'watilah', 'watiyah', 'watsiqah', 'wasikoh', 'welas', 'wening', 'widi', 'widia', 'widhia', 'widhiya', 'widiya', 'widiasari', 'widiawat', 'widy', 'wikayah', 'wilona', 'willona', 'windi', 'windiawati', 'windiasari', 'wina', 'wini', 'wirastuti', 'wiqayah', 'wikoyah', 'wiwin', 'windy', 'wulan', 'wulandari',
            'xxx', 'xnxx', 'xyz', 'xyzz','tzy','tyz', 'mojang', 'gemoy','imut','kebi','cabi','tembem','cantik','cans','canss','gelis','geulis','ytta','kasep','ganteng','wibu','gojo','gojosatoru','santik', 'gerengseng', 'bokep', 'ewe', 'xtc', 'brigez', 'garutpride', 'bandungpride', 'sundapride', '1', '2', '3', '4', '5', '6', '7', '8', '9', '01', '02', '03', '04', '05', '06', '07', '08', '09', '010', '00', '99', '999', '000', '0000', '12', '123', '1234', '12345', '123456', 'bandung', 'banung', 'sukabumi', 'tasik', 'tasikmalaya', 'toblong', 'peundeuy', 'singajaya', 'pameungpeuk', 'cibalong', 'pamempek', 'simpang', 'cisompet', 'banyarwangi', 'cinangsi', 'cisurupan', 'saribakti', 'cikajang',
            'yani', 'yanti', 'yanti', 'yanty', 'yasira', 'yeni', 'ytta', 'yuli', 'yulli', 'yulia', 'yuliya', 'yulya', 'yully', 'yulianti', 'yuliyanti', 'yusria', 'yusriah', 'yusrina', 'yuni', 'yunita', 'yuningsih', 'yuyu', 'yuyun',
            'zahra', 'zafira', 'zafirah', 'zahira', 'zahirah', 'zahiyah', 'zahra', 'zahrani', 'zahrany', 'zahwa', 'zaidah', 'zainab', 'zainnab', 'zairah', 'zaitun', 'zakiah', 'zakyah', 'zakiyyah', 'zenab', 'zennab', 'zalfa', 'zalpa', 'zalva', 'zalsa', 'zannah', 'zara', 'zariah', 'zaskia', 'zaskiya', 'zaskya', 'zaskiani', 'zaskiyani', 'zizah', 'zaynah', 'zayanah', 'zayyanah', 'zenia', 'zera', 'zhafira', 'zhafirah', 'zharifa', 'zharifah', 'zia', 'zizi', 'zyzy', 'zubaidah', 'zuhrah', 'zulfa', 'zulpa', 'zulva', 'zunaira', 'zunea', 'zunnea',
            'aceh', 'indonesia', 'konoha', 'bali', 'cilegon', 'serang', 'tangerang', 'jakarta', 'jambi', 'bandung', 'bekasi', 'bogor', 'cimahi', 'cirebon', 'depok', 'sukabumi', 'tasik', 'tasikmalaya', 'banjar', 'magelang', 'pekalongan', 'semarang', 'surakarta', 'tegal', 'garut', 'blitar', 'kediri', 'madiun', 'malang', 'mojokerto', 'pasuruan', 'surabaya', 'batam', 'lampung', 'bima', 'mataram', 'kupang', 'bali', 'ntt', 'ntb', 'sorong', 'jayapura', 'maluku', 'papua', 'dumai', 'riau', 'pekanbaru', 'sumatra', 'sulawesi', 'makassar', 'kalimanta','kalimantan', 'bitung', 'manado', 'bukittinggi', 'padang', 'palembang', 'binjai', 'medan', 'padang', 'pematangsiantar', 'sibolga', 'tebingtinggi'
        ]
    
    def _apply_random_format(self, name: str) -> str:
        """
        pattern password randomization 
        
        Params:
            name: example or sample string password.
            
        Return:
            your generated password.
        """
        templates = [                                                   # PATTERN
            lambda x: f"{x}{random.randint(10,99)}",                    # [string_name][number 10 - 99]
            lambda x: f"{x}{random.choice(self.code)}",                 # [string_name][country_code]
            lambda x: f"{x}!{x[0]}{random.randint(1,9)}{x[-1]}",        # [string_name]![first char string name][number 1, 0][last char string name]
            lambda x: f"{x}{random.choice(self.wordlist)}",             # [string_name][random wordlist]
            lambda x: f"{x}{random.randint(2000, 2026)}",               # [string_name][number 2000 - 2026]
            lambda x: f"{x}{x[-2:]}",                                   # [string_name][2 last char string name]
            lambda x: f"{random.choice(self.wordlist)}-{x}",            # [random wordlist]-[string name]
            lambda x: f"{x[:3]}_{x[-3:]}",                              # [take 3 first char]_[take 3 first char]
            lambda x: f"{x}{random.randint(1, 10000)}",                 # [string_name][random number 1 - 10.000]
            lambda x: f"{x}{random.choice(self.sifat)}",                # [string_name][random characteristic]
            lambda x: f"{self.sifat}_{x}{random.randint(1, 10000)}",    # [random characteristic]_[string name][number 1 - 10.000]
            lambda x: f"{self.benda}{random.randint(2000, 3000)}",      # [random object name][number 2000 - 3000]
        ]
        
        return random.choice(templates)(name)
    
    def randomize(self) -> str:
        """
        return randomzied password.
        """
        return self._apply_random_format(name=random.choice(self.wordlist))
    
if __name__ == '__main__':
    Generate = Generator()
    for _ in range(10):
        result = Generate.randomize()
        print(f"Your password is : {result}")